[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force canonical host: redirect apex -> www (preserve path/query)
[[redirects]]
  from = "/*"
  to = "https://www.ttrplobby.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["ttrplobby.com"] }

