name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          run_install: false

      - name: Setup Node (cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      # keep or remove the steps below as needed
      - name: Type check
        working-directory: frontend
        run: pnpm run typecheck || true  # remove "|| true" if you want failures to block

      - name: Lint
        working-directory: frontend
        run: pnpm run lint || true        # remove "|| true" if you want failures to block

      - name: Test
        working-directory: frontend
        run: pnpm test --if-present || true

