# Example: .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          # point caching at your monorepo frontend lockfile
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # match what you declared in package.json
          version: 10.17.1
          run_install: false

      - name: Install deps (frontend)
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build (frontend)
        working-directory: frontend
        run: pnpm run build
