name: Build & Deploy to Netlify (Plugin Build)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- .github/workflows ----"
          ls -la .github/workflows || true
          echo "---- frontend ----"
          ls -la frontend || true
          echo "---- frontend/src/app ----"
          ls -la frontend/src/app || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install deps (uses lockfile)
        working-directory: frontend
        run: npm ci

      - name: Verify deps
        working-directory: frontend
        run: |
          test -d node_modules && echo "node_modules present" || (echo "node_modules missing" && exit 1)
          jq -r '.scripts' package.json

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      # Run Netlify’s Next.js plugin locally (uses netlify.toml at REPO ROOT)
      - name: Netlify Build (with plugin)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify build --context production --debug

      - name: Show Netlify build output
        run: |
          echo "---- .netlify/build ----"
          ls -la .netlify/build || true
          echo "---- .netlify/functions ----"
          ls -la .netlify/functions || true

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir ".netlify/build" --message "CI deploy $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
