# .github/workflows/deploy.yml
name: Build & Deploy to Netlify (pnpm)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: netlify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Netlify deploy credentials (set these in GitHub → Settings → Secrets and variables → Actions)
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
      # Frontend runtime/build env (also set these as GitHub Action secrets)
      NEXT_PUBLIC_SUPABASE_URL:      ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          run_install: false

      - name: Setup Node (cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install deps (frontend)
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Print debug info
        working-directory: frontend
        run: |
          set -euxo pipefail
          node -v
          pnpm -v
          echo "lockfile:" && ls -la pnpm-lock.yaml || true
          echo "netlify.toml:" && (cat netlify.toml || true)
          echo ".next exists before build?"; ls -la .next || true

      # Use explicit 'netlify' binary to avoid pnpm dlx multiple-bins error
      - name: Deploy to Netlify (prod)
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ env.NETLIFY_SITE_ID }}
          NEXT_PUBLIC_SUPABASE_URL:      ${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          set -euxo pipefail
          pnpm dlx --package=netlify-cli netlify --version
          pnpm dlx --package=netlify-cli netlify deploy --prod --build \
            --auth "$NETLIFY_AUTH_TOKEN" \
            --site "$NETLIFY_SITE_ID" \
            --debug
