# File: .github/workflows/deploy.yml
name: Build & Deploy to Netlify (Plugin Build, cached)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Provided via GitHub Secrets (Settings → Secrets and variables → Actions)
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
      # If you need public envs at build time, add them here:
      # NEXT_PUBLIC_API_URL: https://api.ttrplobby.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (pre-install)
        run: |
          set -euxo pipefail
          echo "PWD:" && pwd
          echo "--- ROOT ---" && ls -la
          echo "--- frontend ---" && ls -la frontend || true
          echo "Lockfile present?" && (test -f frontend/package-lock.json && echo YES || echo NO)

      - name: Setup Node (use npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Restore Next.js incremental build cache
      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: frontend/.next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}-${{ github.ref_name }}
          restore-keys: |
            next-cache-${{ runner.os }}-${{ github.ref_name }}-
            next-cache-${{ runner.os }}-

      # Restore Netlify cache (scoped to frontend/)
      - name: Restore Netlify cache
        uses: actions/cache@v4
        with:
          path: frontend/.netlify/cache
          key: netlify-cache-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}-${{ github.ref_name }}
          restore-keys: |
            netlify-cache-${{ runner.os }}-${{ github.ref_name }}-
            netlify-cache-${{ runner.os }}-

      - name: Node & npm versions
        run: |
          set -euxo pipefail
          node -v
          npm -v

      - name: Install deps (ci OR install)
        working-directory: frontend
        run: |
          set -euxo pipefail
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          test -d node_modules && echo "node_modules present"

      # ✅ Ensure Netlify CLI + runtime helpers for Next.js plugin exist in CI
      - name: Ensure Netlify CLI + bootstrap helper
        working-directory: frontend
        run: |
          set -euxo pipefail
          npm i -D netlify-cli@^17 @netlify/edge-functions-bootstrap@latest @netlify/plugin-nextjs@latest

      - name: Netlify Build (with @netlify/plugin-nextjs)
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ env.NETLIFY_SITE_ID }}
        run: |
          set -euxo pipefail
          npx netlify build --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --context production --debug

      - name: Show build results
        run: |
          set -euxo pipefail
          echo "frontend/.next:"
          ls -la frontend/.next || true
          echo "frontend/.netlify:"
          ls -la frontend/.netlify || true
          echo "frontend/.netlify/functions:"
          ls -la frontend/.netlify/functions || true
          echo "frontend/.netlify/cache:"
          ls -la frontend/.netlify/cache || true

      # ✅ Deploy using the plugin output; let Netlify handle publish dir
      - name: Deploy to Netlify (prod)
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ env.NETLIFY_SITE_ID }}
        run: |
          set -euxo pipefail
          npx netlify deploy --prod --build --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --debug

